// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Password    string             `json:"password"`
	Deleted     pgtype.Bool        `json:"deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
